Create Roadmap.md
Buffer-Finance/Buffer-Docs pull request #7
Opened 2023-03-10 12:01 UTC by RizzJ

changes:

+ short & medium term roadmap added to "Introductions"

2023-03-14 06:46 UTC, bufferfinance requested changes

2023-03-14 06:46 UTC, bufferfinance commented on introduction/Roadmap.md
> +#### Gamification: Referral Program (live on testnet), LeaderBoard, Trader Profiles, and Social Sharing
Referrals are live on mainnet as well

2023-03-16 04:32 UTC, CurieBuffer approved these changes

2023-03-16 04:34 UTC, CurieBuffer approved these changes

2023-03-16 04:37 UTC, merged